### PR TITLE
Make NegotiateAuthClient robust to noise in WWW-Authenticate (#8)

### PR DESCRIPTION
**Pull request by marcoesposito1988**

### CODE REVIEW

**Comment by marcoesposito1988** [comment]
@jbash could you please check if this works for your use case?

**Comment by jbash** [comment]
Actually I'm not sure I can do that soon enough to be useful to you. I found it in a binary download of a third-party Flutter app from F-Droid (AuthPass, source at https://github.com/authpass/authpass), and traced it back to http_auth just by searching for the error message. I have never built a Dart program, a Flutter app, or any standalone Android app, don't have a build environment, and am not sure what it would take to set one up. It's been sort of on my to-learn list for a while, but I don't know when I will get time to actually do it.

**Comment by jbash** [comment]
Thought: I (or you) could submit an issue against AuthPass, since AuthPass would presumably want to pick up any change you made anyway. I could test any build *they* produced against my server. Do you want to do that?

**Comment by marcoesposito1988** [comment]
Sure, I can do that. However, they will also need to reproduce the problem to test the solution. Are you using AuthPass with a self-hosted server, or some other particular configuration that they may not have in their own test suite? How can they otherwise recreate the same scenario?

**Comment by jbash** [comment]
What I had in mind was that they'd build in your patch, and then send me a binary to test. But you or they are welcome to test it against my server. It would be hard for me to give you an actual account, but the bug triggers before you get to the point where you actually need one. https://keepass.kdjf.net

**Comment by marcoesposito1988** [comment]
This is completely fine, as you said this was enough for me to extract the value of the WWW-Authenticate header from your server. I added this string to the test suite.

I will merge this PR and release a new version of the library, so that AuthPass can bump the version. Can you then ping them? As their user you probably have more leverage.

**Comment by jbash** [comment]
Confirmed to work in a test build of AuthPass provided by @hpoul .

**Comment by marcoesposito1988** [comment]
Cool, thanks for reporting back!

**Pull request merged**
